const state={items:[],platform:'all',kind:'all',sort:'price-asc',selected:null,paymentMethod:null,config:null};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n));

async function load(){
  try{
    const [inv,cfg]=await Promise.all([fetch('/api/inventory',{cache:'no-store'}).then(r=>r.json()),fetch('/api/config',{cache:'no-store'}).then(r=>r.json())]);
    if(!inv.ok) throw new Error(inv.error||'Could not load inventory');
    state.items=inv.items; state.config=cfg; $('#statTotal').textContent=inv.items.length; render();
  }catch(e){$('#inventoryGrid').innerHTML=`<div class="loading">${escapeHtml(e.message)}</div>`}
}
function render(){let a=[...state.items];if(state.platform!=='all')a=a.filter(x=>x.platform===state.platform);if(state.kind!=='all')a=a.filter(x=>x.kind===state.kind);if(state.sort==='price-asc')a.sort((x,y)=>x.sale_price-y.sale_price);if(state.sort==='price-desc')a.sort((x,y)=>y.sale_price-x.sale_price);if(state.sort==='handle')a.sort((x,y)=>x.handle.localeCompare(y.handle));$('#inventoryGrid').innerHTML=a.length?a.map(card).join(''):'<div class="loading">No handles match these filters.</div>';$$('[data-buy]').forEach(b=>b.onclick=()=>openCheckout(Number(b.dataset.buy)))}
function card(x){return `<article class="card"><div class="badges"><span class="badge ${x.platform==='Instagram'?'ig':'tt'}">${x.platform}</span><span class="badge">${x.kind}</span></div><div class="handle">${escapeHtml(x.handle)}</div><div class="price">${money(x.sale_price)}</div><button class="ghost" data-buy="${x.id}">Buy handle</button></article>`}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

$$('#platformFilters button').forEach(b=>b.onclick=()=>{$$('#platformFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.platform=b.dataset.platform;render()});
$$('#kindFilters button').forEach(b=>b.onclick=()=>{$$('#kindFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.kind=b.dataset.kind;render()});
$('#sortSelect').onchange=e=>{state.sort=e.target.value;render()};

function openCheckout(id){state.selected=state.items.find(x=>x.id===id);state.paymentMethod=null;if(!state.selected)return;$('#checkoutHandle').textContent=state.selected.handle;$('#checkoutPrice').textContent=money(state.selected.sale_price);$('#checkoutStatus').className='status';$('#checkoutStatus').textContent='';$('#checkoutForm').reset();renderPayments();$('#checkoutModal').showModal()}
function renderPayments(){const c=state.config?.payments||{};const defs=[['cashapp','Cash App'],['zelle','Zelle'],['paypal','PayPal'],['crypto','Crypto']];$('#paymentMethods').innerHTML=defs.map(([k,n])=>`<button type="button" class="payment-method" data-pay="${k}" ${c[k]?.enabled?'':'disabled'}>${n}</button>`).join('');$('#paymentInstructions').textContent='Choose a payment method.';$$('[data-pay]').forEach(b=>b.onclick=()=>{state.paymentMethod=b.dataset.pay;$$('[data-pay]').forEach(x=>x.classList.remove('active'));b.classList.add('active');showInstructions()})}
function showInstructions(){const p=state.config.payments[state.paymentMethod];const amt=money(state.selected.sale_price);if(!p)return;let t='';if(state.paymentMethod==='cashapp')t=`Send exactly ${amt} to ${p.to}. Add the handle ${state.selected.handle} in the payment note if possible.`;if(state.paymentMethod==='zelle')t=`Send exactly ${amt} by Zelle to ${p.to}. Recipient: ${p.name||'listed recipient'}.`;
if(state.paymentMethod==='paypal')t=`Send exactly ${amt} to ${p.to}. Use the payment type specified by the seller and keep your PayPal transaction ID.`;if(state.paymentMethod==='crypto')t=`Send exactly the USD-equivalent of ${amt} using ${p.network}: ${p.address}. Confirm the network before sending and paste the transaction hash below.`;$('#paymentInstructions').textContent=t}

$('#checkoutForm').addEventListener('submit',async e=>{e.preventDefault();if(!state.paymentMethod){setStatus('Choose a payment method first.',false);return}const btn=$('#submitOrder');btn.disabled=true;btn.textContent='Submitting…';setStatus('Creating your order…',true);try{const payload={inventoryId:state.selected.id,email:$('#buyerEmail').value.trim(),paymentMethod:state.paymentMethod,payerName:$('#payerName').value.trim(),paymentRef:$('#paymentRef').value.trim(),note:$('#buyerNote').value.trim()};const r=await fetch('/api/order',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Order could not be created');$('#checkoutStatus').className='status ok';$('#checkoutStatus').innerHTML=`<div class="order-success"><div>Order submitted. Your order ID is</div><div class="order-id">${escapeHtml(j.orderId)}</div><p>Payment still needs manual verification. Keep this ID for support.</p></div>`;btn.style.display='none';await refreshInventory()}catch(err){setStatus(err.message,false)}finally{btn.disabled=false;btn.textContent='I sent payment — submit order'}});
function setStatus(msg,ok){const el=$('#checkoutStatus');el.className='status '+(ok?'ok':'err');el.textContent=msg}
async function refreshInventory(){try{const inv=await fetch('/api/inventory',{cache:'no-store'}).then(r=>r.json());if(inv.ok){state.items=inv.items;render()}}catch{}}

$('#openOrders').onclick=()=>{$('#trackResult').textContent='';$('#trackModal').showModal()};$('#trackBtn').onclick=async()=>{const id=$('#trackOrderId').value.trim();const el=$('#trackResult');if(!id)return;el.textContent='Checking…';el.className='status';try{const r=await fetch('/api/status?orderId='+encodeURIComponent(id),{cache:'no-store'});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Order not found');el.className='status ok';el.innerHTML=`<span class="pill">${escapeHtml(j.status)}</span> &nbsp; ${escapeHtml(j.handle)}<br>${j.message?escapeHtml(j.message):''}`}catch(e){el.className='status err';el.textContent=e.message}};
load();
