const TELEGRAM_API='https://api.telegram.org';
function env(name,required=true){const v=process.env[name];if(required&&!v)throw new Error(`Missing environment variable: ${name}`);return v||''}
function sbHeaders(extra={}){return {apikey:env('SUPABASE_SERVICE_ROLE_KEY'),Authorization:`Bearer ${env('SUPABASE_SERVICE_ROLE_KEY')}`,'Content-Type':'application/json',...extra}}
async function sb(path,options={}){const r=await fetch(`${env('SUPABASE_URL').replace(/\/$/,'')}/rest/v1/${path}`,{...options,headers:sbHeaders(options.headers||{})});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok){const e=new Error(data?.message||data?.hint||`Database error ${r.status}`);e.status=r.status;throw e}return data}
async function telegram(text){const token=env('TELEGRAM_BOT_TOKEN',false),chat=env('TELEGRAM_CHAT_ID',false);if(!token||!chat)return false;const r=await fetch(`${TELEGRAM_API}/bot${token}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:chat,text,parse_mode:'HTML',disable_web_page_preview:true})});return r.ok}
function html(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function sendEmail({to,subject,htmlBody}){const key=env('RESEND_API_KEY',false),from=env('FROM_EMAIL',false);if(!key||!from)return {sent:false,reason:'Email is not configured'};const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[to],subject,html:htmlBody})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.message||'Email delivery failed');return {sent:true,id:data.id}}
function adminOk(secret){const expected=env('ADMIN_SECRET',false);return Boolean(expected&&secret&&secret===expected)}
function methodLabel(m){return ({cashapp:'Cash App',zelle:'Zelle',paypal:'PayPal',crypto:'Crypto'})[m]||m}
module.exports={env,sb,telegram,sendEmail,adminOk,html,methodLabel};