const {sb,telegramApi,env,html,methodLabel}=require('../lib/server');

const SITE=(env('SITE_URL',false)||'https://mikyemedia.com').replace(/\/$/,'');
const ORDER_SELECT='public_id,status,buyer_email,payment_method,payer_name,payment_ref,buyer_note,created_at,reserved_until,payment_verified_at,secured_at,fulfilled_at,list_price,sale_amount,discount_code,discount_amount,inventory(id,handle,platform,kind,source,cost,sale_price,status,reserved_until)';

function authorizedChat(chatId){return String(chatId||'')===String(env('TELEGRAM_CHAT_ID',false)||'')}
function stage(o){if(o.status==='fulfilled')return '✅ Fulfilled';if(o.status==='cancelled')return '❌ Cancelled';if(o.secured_at)return '📦 Secured — ready to fulfill';if(o.payment_verified_at)return '💰 Payment verified — secure the handle';return '⏳ Awaiting payment verification'}
function paidAmount(o){return Number(o.sale_amount??o.inventory?.sale_price??0)}
function profit(o){return paidAmount(o)-Number(o.inventory?.cost||0)}
function fulfillmentUrl(id){return `${SITE}/admin.html?order=${encodeURIComponent(id)}`}
function keyboard(o,confirmRelease=false){if(o.status!=='pending')return {inline_keyboard:[[{text:'🔄 Refresh',callback_data:`refresh:${o.public_id}`}]]};if(confirmRelease)return {inline_keyboard:[[{text:'⚠️ CONFIRM RELEASE',callback_data:`release:${o.public_id}`}],[{text:'← Keep order',callback_data:`refresh:${o.public_id}`}]]};const rows=[];if(!o.payment_verified_at)rows.push([{text:'💰 Mark paid',callback_data:`paid:${o.public_id}`},{text:'🔄 Refresh',callback_data:`refresh:${o.public_id}`}]);else if(!o.secured_at)rows.push([{text:'📦 Mark secured',callback_data:`secured:${o.public_id}`},{text:'🔄 Refresh',callback_data:`refresh:${o.public_id}`}]);else rows.push([{text:'✉️ Fulfill order',url:fulfillmentUrl(o.public_id)},{text:'🔄 Refresh',callback_data:`refresh:${o.public_id}`}]);if(!o.secured_at)rows.push([{text:'✉️ Open admin',url:fulfillmentUrl(o.public_id)},{text:'❌ Release',callback_data:`releaseask:${o.public_id}`}]);else rows.push([{text:'❌ Release instead',callback_data:`releaseask:${o.public_id}`}]);return {inline_keyboard:rows}}
function orderText(o){const i=o.inventory||{},paid=paidAmount(o),list=Number(o.list_price??i.sale_price??0),discount=Number(o.discount_amount||0);const promo=discount>0?`\n<b>Promo:</b> ${html(o.discount_code||'LAUNCH15')} (-$${discount.toFixed(2)})\n<b>Customer pays:</b> $${paid.toFixed(2)}`:'';return `🛒 <b>MIKYE MEDIA ORDER</b>\n\n<b>Order:</b> ${html(o.public_id)}\n<b>Handle:</b> ${html(i.handle||'—')} (${html(i.platform||'—')} ${html(i.kind||'')})\n<b>Supplier:</b> ${html(i.source||'—')}\n<b>Your cost:</b> $${Number(i.cost||0).toFixed(2)}\n<b>List price:</b> $${list.toFixed(2)}${promo}\n<b>Gross profit:</b> $${profit(o).toFixed(2)}\n\n<b>Payment:</b> ${html(methodLabel(o.payment_method))}\n<b>Sender:</b> ${html(o.payer_name)}\n<b>Reference:</b> ${html(o.payment_ref)}\n<b>Buyer:</b> ${html(o.buyer_email)}${o.buyer_note?`\n<b>Note:</b> ${html(o.buyer_note)}`:''}\n\n<b>Stage:</b> ${stage(o)}`}
async function getOrder(id){const rows=await sb(`orders?select=${ORDER_SELECT}&public_id=eq.${encodeURIComponent(String(id||'').trim().toUpperCase())}&limit=1`,{method:'GET'});return rows?.[0]||null}
async function send(chatId,text,replyMarkup){return telegramApi('sendMessage',{chat_id:chatId,text,parse_mode:'HTML',disable_web_page_preview:true,...(replyMarkup?{reply_markup:replyMarkup}:{})})}
async function edit(chatId,messageId,o,confirmRelease=false){return telegramApi('editMessageText',{chat_id:chatId,message_id:messageId,text:orderText(o),parse_mode:'HTML',disable_web_page_preview:true,reply_markup:keyboard(o,confirmRelease)})}
async function answer(id,text,showAlert=false){return telegramApi('answerCallbackQuery',{callback_query_id:id,text,show_alert:showAlert}).catch(()=>null)}

async function listOrders(chatId,mode){let filters='status=eq.pending';let title='PENDING ORDERS';if(mode==='unpaid'){filters+='&payment_verified_at=is.null';title='AWAITING PAYMENT CHECK'}if(mode==='paid'){filters+='&payment_verified_at=not.is.null&secured_at=is.null';title='PAID — NEEDS SECURING'}if(mode==='secured'){filters+='&secured_at=not.is.null';title='SECURED — READY TO FULFILL'}const rows=await sb(`orders?select=${ORDER_SELECT}&${filters}&order=created_at.desc&limit=15`,{method:'GET'});if(!rows?.length)return send(chatId,`✅ <b>${title}</b>\n\nNothing here right now.`);const body=rows.map(o=>`<b>${html(o.public_id)}</b> · ${html(o.inventory?.handle||'—')} · $${paidAmount(o).toFixed(2)}\n${stage(o)}`).join('\n\n');return send(chatId,`📋 <b>${title}</b>\n\n${body}\n\nUse <code>/order ORDERID</code> to open one.`)}
function laDayKey(d){return new Intl.DateTimeFormat('en-US',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
async function today(chatId){const since=new Date(Date.now()-48*60*60*1000).toISOString();const rows=await sb(`orders?select=${ORDER_SELECT}&created_at=gte.${encodeURIComponent(since)}&order=created_at.desc&limit=500`,{method:'GET'});const key=laDayKey(new Date());const day=(rows||[]).filter(o=>laDayKey(new Date(o.created_at))===key);const fulfilled=day.filter(o=>o.status==='fulfilled');const revenue=fulfilled.reduce((s,o)=>s+paidAmount(o),0);const costs=fulfilled.reduce((s,o)=>s+Number(o.inventory?.cost||0),0);const discounts=fulfilled.reduce((s,o)=>s+Number(o.discount_amount||0),0);const unpaid=day.filter(o=>o.status==='pending'&&!o.payment_verified_at).length;const paid=day.filter(o=>o.status==='pending'&&o.payment_verified_at&&!o.secured_at).length;const secured=day.filter(o=>o.status==='pending'&&o.secured_at).length;return send(chatId,`📊 <b>TODAY — LOS ANGELES</b>\n\n<b>Orders:</b> ${day.length}\n<b>Fulfilled:</b> ${fulfilled.length}\n<b>Revenue:</b> $${revenue.toFixed(2)}\n<b>Launch discounts:</b> $${discounts.toFixed(2)}\n<b>Supplier cost:</b> $${costs.toFixed(2)}\n<b>Gross profit:</b> $${(revenue-costs).toFixed(2)}\n\n⏳ Awaiting payment: ${unpaid}\n💰 Paid / needs securing: ${paid}\n📦 Ready to fulfill: ${secured}`)}

async function handleMessage(message){const chatId=message?.chat?.id;if(!authorizedChat(chatId))return;const raw=String(message.text||'').trim();const cmd=raw.split(/\s+/)[0].toLowerCase().split('@')[0];if(cmd==='/start'||cmd==='/help')return send(chatId,'🤖 <b>MIKYE MEDIA SALES BOT</b>\n\n/orders — all open orders\n/pending — waiting for payment verification\n/paid — paid, still needs securing\n/secured — ready to fulfill\n/today — today’s sales + profit\n/order ORDERID — open one order\n\nNew website orders also arrive here with action buttons.');if(cmd==='/orders')return listOrders(chatId,'all');if(cmd==='/pending')return listOrders(chatId,'unpaid');if(cmd==='/paid')return listOrders(chatId,'paid');if(cmd==='/secured')return listOrders(chatId,'secured');if(cmd==='/today')return today(chatId);if(cmd==='/order'){const id=raw.split(/\s+/)[1];if(!id)return send(chatId,'Usage: <code>/order ORDERID</code>');const o=await getOrder(id);if(!o)return send(chatId,'❌ Order not found.');return send(chatId,orderText(o),keyboard(o))}return send(chatId,'Unknown command. Send /help for the command list.')}

async function handleCallback(q){const chatId=q?.message?.chat?.id,messageId=q?.message?.message_id;if(!authorizedChat(chatId)){await answer(q.id,'Not authorized.',true);return}const [action,idRaw]=String(q.data||'').split(':');const id=String(idRaw||'').toUpperCase();let o=await getOrder(id);if(!o){await answer(q.id,'Order not found.',true);return}if(action==='refresh'){await answer(q.id,'Updated');return edit(chatId,messageId,o)}if(action==='releaseask'){await answer(q.id,'Confirm below');return edit(chatId,messageId,o,true)}if(action==='paid'){if(o.status!=='pending'){await answer(q.id,`Order is ${o.status}.`,true);return}if(!o.payment_verified_at){const now=new Date().toISOString(),extended=new Date(Date.now()+7*24*60*60*1000).toISOString();await sb(`orders?public_id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({payment_verified_at:now,reserved_until:extended})});await sb(`inventory?id=eq.${o.inventory.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({reserved_until:extended})})}o=await getOrder(id);await answer(q.id,'Payment marked verified.');return edit(chatId,messageId,o)}if(action==='secured'){if(o.status!=='pending'){await answer(q.id,`Order is ${o.status}.`,true);return}if(!o.payment_verified_at){await answer(q.id,'Mark payment verified first.',true);return}if(!o.secured_at)await sb(`orders?public_id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({secured_at:new Date().toISOString()})});o=await getOrder(id);await answer(q.id,'Handle marked secured.');return edit(chatId,messageId,o)}if(action==='release'){if(o.status!=='pending'){await answer(q.id,`Order is ${o.status}.`,true);return}await sb(`orders?public_id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'cancelled'})});await sb(`inventory?id=eq.${o.inventory.id}&status=neq.sold`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'available',reserved_until:null})});o=await getOrder(id);await answer(q.id,'Order released.');return edit(chatId,messageId,o)}await answer(q.id,'Unknown action.',true)}

module.exports=async function handler(req,res){if(req.method!=='POST')return res.status(405).json({ok:false});const expected=env('TELEGRAM_WEBHOOK_SECRET',false);const supplied=req.headers['x-telegram-bot-api-secret-token'];if(!expected||supplied!==expected)return res.status(401).json({ok:false});try{const update=req.body||{};if(update.callback_query)await handleCallback(update.callback_query);else if(update.message)await handleMessage(update.message);return res.status(200).json({ok:true})}catch(e){console.error('Telegram webhook error',e);return res.status(200).json({ok:true})}};
